/*
ANIMATION TWEAKS GNOME EXTENSION PROFILES
=========================================

!!!  Do not Edit this file !!!

This file is automatically moodified by prefs.js to when extension profiles are modified.

*/

var AnimationTweaksExtensionProfileDefault=class AnimationTweaksExtensionProfileDefault{
constructor(){
this.animationTweaksExtensionProfileName="Default";
this.firstUse=true;
this.version=12;
this.openingEffectEnabled=true;
this.closingingEffectEnabled=false;
this.minimizingEffectEnabled=false;
this.unMinimizingEffectEnabled=false;
this.movingEffectEnabled=false;
this.focussingEffectEnabled=false;
this.defocussingEffectEnabled=false;
this.useApplicationProfiles=false;
this.nameList=[];
this.appList=[];
this.normalWindowopenProfileRaw=["|","F","Scale Down","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","0.5","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.normalWindowcloseProfileRaw=["|","F","Scale Up","1","0.0","0.0","0.0","0.0","0.0","0.300","0","1.0","0.5","0.0","0.0","0.0","0.0","0.0","0.0","easeInCubic"];
this.normalWindowminimizeProfileRaw=["|","F","Slide Down","1","0.0","0.0","0.0","0.0","0.0","0.300","0","1.0","1.0","0.0","0.2","0.0","0.0","0.0","0.0","easeInCubic"];
this.normalWindowunminimizeProfileRaw=["|","F","Slide Up","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","1.0","0.0","0.2","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","-0.2","0.0","0.0","0.0","0.0","easeOutCubic"];
this.normalWindowmovestartProfileRaw=["|","F","Fade","2","0.0","0.0","0.0","0.0","0.0","0.300","220",".9999",".9999","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.normalWindowfocusProfileRaw=["|","F","Inflate","2","0.5","0.5","0.0","0.0","0.0","0.025","255","1.02","1.02","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.5","0.5","0.0","0.0","0.0","0.025","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeInCubic"];
this.normalWindowdefocusProfileRaw=["|","F","Deflate","2","0.5","0.5","0.0","0.0","0.0","0.025","255","0.97","0.97","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.5","0.5","0.0","0.0","0.0","0.025","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeInCubic"];
this.dialogWindowopenProfileRaw=["|","F","Fold Out Sideways","2","0.5","0.0","0.0","0.0","0.0","0.001","255","0.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.5","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.dialogWindowcloseProfileRaw=["|","F","Fold In Sideways","1","0.5","0.0","0.0","0.0","0.0","0.300","255","0.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.dialogWindowminimizeProfileRaw=["|","F","Slide Down","1","0.0","0.0","0.0","0.0","0.0","0.300","0","1.0","1.0","0.0","0.2","0.0","0.0","0.0","0.0","easeInCubic"];
this.dialogWindowunminimizeProfileRaw=["|","F","Slide Up","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","1.0","0.0","0.2","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","-0.2","0.0","0.0","0.0","0.0","easeOutCubic"];
this.dialogWindowmovestartProfileRaw=["|","F","Fade","2","0.0","0.0","0.0","0.0","0.0","0.300","220","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.dialogWindowfocusProfileRaw=["|","F","Inflate","2","0.5","0.5","0.0","0.0","0.0","0.025","255","1.02","1.02","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.5","0.5","0.0","0.0","0.0","0.025","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeInCubic"];
this.dialogWindowdefocusProfileRaw=["|","F","Deflate","2","0.5","0.5","0.0","0.0","0.0","0.025","255","0.97","0.97","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.5","0.5","0.0","0.0","0.0","0.025","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeInCubic"];
this.modaldialogWindowopenProfileRaw=["|","F","Slide Down","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","1.0","0.0","-0.2","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.2","0.0","0.0","0.0","0.0","easeOutCubic"];
this.modaldialogWindowcloseProfileRaw=["|","F","Slide Up","1","0.0","0.0","0.0","0.0","0.0","0.300","0","1.0","1.0","0.0","-0.2","0.0","0.0","0.0","0.0","easeInCubic"];
this.modaldialogWindowminimizeProfileRaw=["|","F","Slide Down","1","0.0","0.0","0.0","0.0","0.0","0.300","0","1.0","1.0","0.0","0.2","0.0","0.0","0.0","0.0","easeInCubic"];
this.modaldialogWindowunminimizeProfileRaw=["|","F","Slide Up","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","1.0","0.0","0.2","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","-0.2","0.0","0.0","0.0","0.0","easeOutCubic"];
this.modaldialogWindowmovestartProfileRaw=["|","F","Fade","2","0.0","0.0","0.0","0.0","0.0","0.300","220","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.modaldialogWindowfocusProfileRaw=["|","F","Inflate","2","0.5","0.5","0.0","0.0","0.0","0.025","255","1.02","1.02","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.5","0.5","0.0","0.0","0.0","0.025","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeInCubic"];
this.modaldialogWindowdefocusProfileRaw=["|","F","Deflate","2","0.5","0.5","0.0","0.0","0.0","0.025","255","0.97","0.97","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.5","0.5","0.0","0.0","0.0","0.025","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeInCubic"];
this.dropdownmenuWindowopenProfile=["|","T","Scale Down","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","0.5","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.250","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.popupmenuWindowopenProfile=["|","T","Scale Down","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","0.5","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.250","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.comboWindowopenProfile=["|","T","Scale Down","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","0.5","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.250","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.splashscreenWindowopenProfile=["|","T","Zoom In","2","0.5","0.5","0.0","0.0","0.0","0.001","0","0.8","0.8","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.5","0.5","0.0","0.0","0.0","0.250","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.tooltipWindowopenProfile=["|","T","Slide Up","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","1.0","0.0","0.1","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.overrideotherWindowopenProfile=["|","T","Scale Down","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","0.5","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.250","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.notificationbannerWindowopenProfile=["|","F","Fade In","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.notificationbannerWindowcloseProfile=["|","F","Fade Out","1","0.0","0.0","0.0","0.0","0.0","0.300","0","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.notificationBannerAlignment="2"
this.padosdWindowopenProfile=["|","F","Slide Up","3","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","1.0","0.0","0.2","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.300","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.padosdWindowcloseProfile=["|","F","Scale Up","1","0.0","1.0","0.0","0.0","0.0","0.300","255","1.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.toppanelpopupmenuWindowopenProfile=["|","F","Scale Down","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","0.5","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.250","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.toppanelpopupmenuWindowcloseProfile=["|","F","Scale Up","1","0.0","1.0","0.0","0.0","0.0","0.300","255","1.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.desktoppopupmenuWindowopenProfile=["|","F","Scale Down","2","0.0","0.0","0.0","0.0","0.0","0.001","0","1.0","0.5","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic","0.0","0.0","0.0","0.0","0.0","0.250","255","1.0","1.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.desktoppopupmenuWindowcloseProfile=["|","F","Scale Up","1","0.0","1.0","0.0","0.0","0.0","0.300","255","1.0","0.0","0.0","0.0","0.0","0.0","0.0","0.0","easeOutCubic"];
this.waylandWorkaroundEnabled=false;
this.padOSDHideTime= 1500;
}}//EndOfAnimationTweaksExtensionProfileDefault
