#!/bin/bash

xgettext --from-code utf-8 -k_ -kN_ -o locale/animation-tweaks.pot animation-tweaks@Selenium-H/*.js -o locale/animation-tweaks.pot schemas/*.xml

grep animation-tweaks@Selenium-H/defaultEffectsList.js -e "'|','"| cut -c7-35 | tr \' \" | tr \, " " |sort|uniq >> effect-names.pot
sed -e 's/^/msgid /' -i effect-names.pot
sed -e 's/$/\nmsgstr \"\"\n\n#: Generated by update_pot.sh/' -i effect-names.pot
sed -e 1's/.*/\n#: Generated by update_pot.sh\n&/' -i effect-names.pot 
cat effect-names.pot >> locale/animation-tweaks.pot
rm effect-names.pot

grep animation-tweaks@Selenium-H/metadata.json -e "\"description\":" >> desc.pot
sed -i 's/\"description\":/msgid/' desc.pot
sed -i 's/\",/"/' desc.pot
sed -e 's/$/\nmsgstr \"\"/' -i desc.pot
cat desc.pot >> locale/animation-tweaks.pot
rm desc.pot

for pofile in $(find locale -mindepth 2 | egrep .po); do
    msgmerge -o $pofile.new $pofile locale/animation-tweaks.pot
    mv $pofile.new $pofile
done

